// basic-nuxt-typescript/components/admin/Footer.vue
<script setup lang="ts">

</script>

<template>
    <footer class="bg-gray-800 text-white p-4 flex flex-col md:flex-row justify-between items-center">
        <div class="bg-gray-800 text-white p-4 flex justify-between items-center">
            <p>&copy; 2025 Your Company</p>
            <ul class="flex space-x-4">
                <li><a href="#" class="text-white">Privacy Policy</a></li>
                <li><a href="#" class="text-white">Terms of Service</a></li>
                <li><a href="#" class="text-white">Contact Us</a></li>
            </ul>
        </div>
        <div class="bg-gray-700 text-white p-2 text-center">
            <p>All rights reserved.</p>
        </div>
    </footer>
</template>

<style scoped>

</style>

// basic-nextjs-typescript/src/components/admin/Footer.tsx
import React from 'react'

type Props = {}

export default function Footer({}: Props) {
  return (
    <footer className="bg-white border-t border-gray-200 dark:bg-gray-900 dark:border-gray-700">
      <div className="mx-auto p-4">
        <div className="text-center text-gray-500 dark:text-gray-400">
          © 2023 Your Company. All rights reserved.
        </div>
        <div className="text-center text-gray-500 dark:text-gray-400 mt-2">
            <a href="#" className="hover:underline">Privacy Policy</a> | <a href="#" className="hover:underline">Terms of Service</a>
        </div>
        </div>
    </footer>
  )
}
