// basic-nextjs-typescript/src/components/admin/Footer.tsx
import React from 'react'

type Props = {}

export default function Footer({}: Props) {
  return (
    <footer className="bg-white border-t border-gray-200 dark:bg-gray-900 dark:border-gray-700">
      <div className="mx-auto p-4">
        <div className="text-center text-gray-500 dark:text-gray-400">
          © 2023 Your Company. All rights reserved.
        </div>
        <div className="text-center text-gray-500 dark:text-gray-400 mt-2">
            <a href="#" className="hover:underline">Privacy Policy</a> | <a href="#" className="hover:underline">Terms of Service</a>
        </div>
        </div>
    </footer>
  )
}

// basic-nuxt-typescript/components/Footer.vue
<script setup lang="ts">
    console.log("Footer 555");
</script>

<template>
    <footer>
        <p>&copy; 2025 My Website</p>
        <ul>
            <li><a href="/privacy">Privacy Policy</a></li>
            <li><a href="/terms">Terms of Service</a></li>
        </ul>
    </footer>
</template>

<style scoped>

    footer {
        background-color: #333;
        color: white;
        padding: 10px;
        text-align: center;
    }
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }
    li {
        display: inline;
        margin-right: 20px;
    }
    a {
        color: white;
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }

</style>
